### ISSUE TITLE
[Errno 13] Permission denied: 'buildozer.spec'

### ISSUE THREAD

**Issue by James-E-A** [tshirtman/Buildozer-docker#2]
I'm getting this error when trying to initialize buildozer

````
# docker run -v $PWD:/buildozer tshirtman/buildozer buildozer init .
Unable to find image 'tshirtman/buildozer:latest' locally
latest: Pulling from tshirtman/buildozer
e8a74323e913: Pull complete
5fe91835aea8: Pull complete
4b2aac3e93a5: Pull complete
faefbf4d7e6d: Pull complete
071e113a30b5: Pull complete
1a048b855e51: Pull complete
829bd7645763: Pull complete
7d554ec611e3: Pull complete
b1d419e48fe1: Pull complete
76e320630634: Pull complete
33a1d5268dce: Pull complete
fd9caa6b4813: Pull complete
Digest: sha256:1ecb2632e1a96090fc4ed2d22dbd0b68c3859656b83678eefcab9c4648fb2560
Status: Downloaded newer image for tshirtman/buildozer:latest
Traceback (most recent call last):
  File "/usr/local/bin/buildozer", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/buildozer/__init__.py", line 1048, in run_command
    getattr(self, cmd)(*args)
  File "/usr/local/lib/python2.7/dist-packages/buildozer/__init__.py", line 1092, in cmd_init
    copyfile(join(dirname(__file__), 'default.spec'), 'buildozer.spec')
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: 'buildozer.spec'
````

It happens regardless of whether I have a `buildozer.spec` in `$PWD`

**Comment by James-E-A** [comment]
````
# docker version
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.2
 Git commit:    0520e24
 Built: Wed Mar 21 23:05:52 2018
 OS/Arch:       linux/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   0520e24
  Built:        Wed Mar 21 23:14:54 2018
  OS/Arch:      linux/amd64
  Experimental: false
````

**Comment by robertpro** [comment]
what are the buildozer.spec permissions ?

```bash
ls -l buildozer.spec 
-rw-rw-r-- 1 roberto roberto 7940 Mar 28 23:30 buildozer.spec
```

**Comment by James-E-A** [comment]
Ah, it turns out this was user error on my part: I was using docker-in-docker's volumes incorrectly and the directory wasn't getting passed through at all. Sorry about that!
